import type { Metadata } from 'next'
import Header from './ui/header/Header'
import './styles/reset.css'
import SideBar from './ui/sidebar/SideBar'
import { Provider } from './context/MainContext'

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
      <SideBar />
      <Header />
        {children}
        </Provider>
      </body>
    </html>
  )
}
